---
title: "Installing R/RStudio"
author: "Burrel Vann Jr"
output: 
  html_document: 
    css: markdown3.css
---
<br>

###### Getting RStudio Up and Running
* [**Installing R/RStudio**](installing.html)
* [**Getting Started with RStudio**](getting-started.html)
* [**Reading-in Data**](reading-in-data.html)

###### Univariate/Descriptive Statistics and Assessing Normality
* [**Univariate/Descriptive Statistics & Normality**](univariate-normality.html) [ <a href="https://raw.githubusercontent.com/burrelvannjr/gradstats_sdsu/main/resources/exercises/univariate-normality.R" target="_blank"><i>R Script</i></a> ]

###### Bivariate and Multivariate Statistics
* [**Independent Samples t-Test**](t-test.html) [ <a href="https://raw.githubusercontent.com/burrelvannjr/gradstats_sdsu/main/resources/exercises/t-test.R" target="_blank"><i>R Script</i></a> | [*Example*](t-test-example.html) ]
* [**One-Way Analysis of Variance (ANOVA)**](anova.html) [ <a href="https://raw.githubusercontent.com/burrelvannjr/gradstats_sdsu/main/resources/exercises/anova.R" target="_blank"><i>R Script</i></a> | [*Example*](anova-example.html) ]
* [**Chi Square Test of Independence**](chi-square.html) [ <a href="https://raw.githubusercontent.com/burrelvannjr/gradstats_sdsu/main/resources/exercises/chi-square.R" target="_blank"><i>R Script</i></a> | [*Example*](chi-square-example.html) ]
* [**Correlation**](correlation.html) [ <a href="https://raw.githubusercontent.com/burrelvannjr/gradstats_sdsu/main/resources/exercises/correlation.R" target="_blank"><i>R Script</i></a> | [*Example*](correlation-example.html) ]
* [**Regression**](regression.html) [ <a href="https://raw.githubusercontent.com/burrelvannjr/gradstats_sdsu/main/resources/exercises/regression.R" target="_blank"><i>R Script</i></a> | [*Example*](regression-example.html) ]
<br><br>


#




### What is R?

We will be using [R](https://cran.r-project.org/), an open-source statistical program. Open-source, of course, means that it is free to use. R is a programming language, and the basic R program runs through command-line. To make it easy on first-time users, we will also be  using R's graphical user interface, [RStudio](https://rstudio.com/products/rstudio/download/), that runs R in one of its windows -- without you having to open R. 

### Downloading & Installing R

1. Go to the [**R website**](https://cran.r-project.org/) to download the program. Under the "Download and Install R" section, select the distribution that matches your computer's operating system (macOS/OSX, Windows, Linux). 

    + For Mac Users: On the next page, under the "Files" section, select the first file/link (which should be something like "R-3.x.x.pkg")

    + For Windows Users: On the next page, select the link/word "base". On the following page, select the large link (which should be something like "Download R 3.x.x for Windows")

    + For Linux Users: On the next page, select your specific distribution, and follow the instructions.

2. For all users, install the downloaded R program.

### Downloading & Installing RStudio

1. Next, we will download [**RStudio**](https://rstudio.com/products/rstudio/download/) which is a easily understandable user interface for using R. If you're using a machine (e.g. a non-tablet pc/mac), under "RStudio Desktop" click "Download". Next, it should take you to a page with a "Download" button. Additionaly, under "All Installers" you can select the RStudio download that matches your operating system.

2. After the download is complete, install the RStudio program.

