<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>One-Way ANOVA Example</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="markdown3.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">RStudio Walkthroughs</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-download"></span>
     
    Getting Started
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="installing.html">Downloading/Installing</a>
    </li>
    <li>
      <a href="getting-started.html">Getting Started with RStudio</a>
    </li>
    <li>
      <a href="reading-in-data.html">Reading in Data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-chart-line"></span>
     
    In-Class
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Univariate Statistics</li>
    <li>
      <a href="univariate-normality.html">Descriptive Statistics and Assessing Normality</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Bivariate Statistics</li>
    <li>
      <a href="t-test.html">Independent Samples t-Test</a>
    </li>
    <li>
      <a href="anova.html">One-Way Analysis of Variance (ANOVA)</a>
    </li>
    <li>
      <a href="chi-square.html">Chi Square Test of Independence</a>
    </li>
    <li>
      <a href="correlation.html">Correlation</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Multivariate Statistics</li>
    <li>
      <a href="regression.html">OLS Regression</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-folder-open"></span>
     
    Additional Materials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Bivariate Statistics</li>
    <li>
      <a href="chi-square-gof.html">Chi Square Goodness of Fit</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">One-Way ANOVA Example</h1>

</div>


<hr />
<div
id="is-there-a-mean-difference-in-monthly-income-across-different-racial-groups"
class="section level4">
<h4>Is there a mean difference in monthly income across different racial
groups?</h4>
<p><br></p>
</div>
<div id="the-analysis-of-variance-anova" class="section level3">
<h3>The Analysis of Variance (ANOVA)</h3>
<p>The ANOVA is a bivariate (two variable) test that examines the
differences in means between <strong>three or more</strong> groups, in
effort to see if the differences reflect true differences that we could
expect to find in the population. The resulting test calculates an F
value.</p>
<p>For this example, the ANOVA works because we have have four groups
(black, white, latinx, and other), and we’re examining each group’s mean
monthly income to see if there is a true difference in income amongst
racial groups in the population.</p>
<p><br></p>
<div id="load-the-necessary-stuff" class="section level4">
<h4>Load the Necessary Stuff</h4>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(vannstats)</span></code></pre></div>
<p><br></p>
</div>
<div id="reading-in-the-data" class="section level4">
<h4>Reading in the Data</h4>
<p><img src="anova.png" width="200" alt="ANOVA" /> <br><br><br></p>
<p>In the table (above), we have a total of 20 people, randomly-sampled.
We see that we have a total of 5 people within each racial category
(black, white, latinx, and other), and each individual has a monthly
income value. We can use these data to create a data set, using a
combination of the concatenate, <span
style="color:blue"><code>c()</code></span>, data frame <span
style="color:blue"><code>data.frame</code></span>, and the repeat <span
style="color:blue"><code>rep()</code></span> functions.</p>
<p>The repeat function comes in handy when you have to type out the same
values over and over again. This function has two arguments: 1) the
thing you want to repeat, and 2) the number of times you want to repeat
it.</p>
<p>Using this logic, we can apply the repeat function to create each
variable, concatenating across the various categories of each variable,
and combine these variables into a data frame… as such…</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>race <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">&quot;black&quot;</span>,<span class="dv">5</span>),</span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">&quot;white&quot;</span>,<span class="dv">5</span>),</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">&quot;latinx&quot;</span>,<span class="dv">5</span>),</span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>  <span class="fu">rep</span>(<span class="st">&quot;other&quot;</span>,<span class="dv">5</span>))</span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a>inc <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3670</span>, <span class="dv">3132</span>, <span class="dv">3798</span>, <span class="dv">3929</span>, <span class="dv">3203</span>, <span class="dv">6628</span>, <span class="dv">4702</span>, <span class="dv">4264</span>, <span class="dv">4063</span>, <span class="dv">4847</span>, <span class="dv">2239</span>, <span class="dv">3143</span>, <span class="dv">4580</span>, <span class="dv">3158</span>, <span class="dv">3471</span>, <span class="dv">3131</span>, <span class="dv">4462</span>, <span class="dv">3901</span>, <span class="dv">3410</span>, <span class="dv">4927</span>)</span></code></pre></div>
<p>Next, we merge the variables into one data frame, using the
following:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(race,inc)</span></code></pre></div>
<p>Now we can call the data…</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>data</span></code></pre></div>
<pre><code>##      race  inc
## 1   black 3670
## 2   black 3132
## 3   black 3798
## 4   black 3929
## 5   black 3203
## 6   white 6628
## 7   white 4702
## 8   white 4264
## 9   white 4063
## 10  white 4847
## 11 latinx 2239
## 12 latinx 3143
## 13 latinx 4580
## 14 latinx 3158
## 15 latinx 3471
## 16  other 3131
## 17  other 4462
## 18  other 3901
## 19  other 3410
## 20  other 4927</code></pre>
<p><br></p>
</div>
</div>
<div id="assumptions-and-diagnostics-for-the-anova"
class="section level3">
<h3>Assumptions and Diagnostics for the ANOVA</h3>
<p>The assumptions for an ANOVA are…</p>
<ul>
<li>Independence of Observations</li>
<li>Equal Sample Sizes</li>
<li>Homogeneity of Variance</li>
<li>Normality</li>
</ul>
<div id="independence-of-observations-examine-data-collection-strategy"
class="section level5">
<h5>1. Independence of Observations (Examine Data Collection
Strategy)</h5>
<ul>
<li>Groups are not related or dependent upon each other. Cases can’t be
in more than one group. No ties between observations. Examine data
collection strategy to see if there are linkages between observations.
<ul>
<li><span style="color:red">These data were randomly sampled.
<code>Therefore, we meet the assumption of independence of observations</code>.</span>
<br></li>
</ul></li>
</ul>
</div>
<div id="equal-sample-sizes-examine-n-for-each-group"
class="section level5">
<h5>2. Equal Sample Sizes (Examine N for each group)</h5>
<ul>
<li>The number of cases in each group should be relatively similar.</li>
</ul>
</div>
<div id="homogeneity-of-variance-examine-sd2-for-each-group"
class="section level5">
<h5>3. Homogeneity of Variance (Examine SD<sup>2</sup> for each
group)</h5>
<ul>
<li>All groups have approximately equal variances (SD<sup>2</sup>). The
distributions (or spread) for the groups are approximately equal. Keppel
&amp; Zedeck (1989) suggest that variance comparison should not exceed
10:1 ratio (<em>or… alternatively, the SDs, when compared, should not
exceed around a 3:1 ratio</em>). For both of the above assumptions, we
can examine the univariate data table, broken out by group:</li>
</ul>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">describeBy</span>(data<span class="sc">$</span>inc, data<span class="sc">$</span>race)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: black
##    vars n   mean     sd median trimmed    mad  min  max range  skew kurtosis     se
## X1    1 5 3546.4 358.68   3670  3546.4 383.99 3132 3929   797 -0.16    -2.17 160.41
## ------------------------------------------------------------------ 
## group: latinx
##    vars n   mean    sd median trimmed    mad  min  max range skew kurtosis    se
## X1    1 5 3318.2 842.1   3158  3318.2 464.05 2239 4580  2341 0.25    -1.45 376.6
## ------------------------------------------------------------------ 
## group: other
##    vars n   mean     sd median trimmed    mad  min  max range skew kurtosis     se
## X1    1 5 3966.2 738.26   3901  3966.2 831.74 3131 4927  1796 0.13    -1.99 330.16
## ------------------------------------------------------------------ 
## group: white
##    vars n   mean     sd median trimmed    mad  min  max range skew kurtosis     se
## X1    1 5 4900.8 1016.5   4702  4900.8 649.38 4063 6628  2565 0.82    -1.21 454.59</code></pre>
<ul>
<li><span style="color:red">The sample size for each group is exactly
the same for all groups. Therefore,
<code>we have met the assumtption for equal sample sizes</code>. We can
also see that, when comparing the SD for all groups, there is not a
ratio larger than 3:1. For these data, the largest discrepancy between
SDs for each group is between black individuals (SD = 358.68) and white
individuals (SD = 1016.5), which is less than the 3:1 ratio suggested.
Therefore,
<code>we have met the assumption for homogeneity of variance</code>.</span>
<br></li>
</ul>
</div>
<div
id="normality-examine-plots-histogram-q-q-normality-plots-box-and-whiskers-plots"
class="section level5">
<h5>4. Normality (Examine Plots: Histogram, Q-Q Normality Plots,
Box-and-Whiskers Plots)</h5>
<ul>
<li>Distribution must be relatively normal.</li>
</ul>
</div>
<div id="a.-histogram" class="section level5">
<h5>4a. Histogram</h5>
<p>Plot the histogram for <em>Monthly Income</em> (Y variable) broken
out by <em>Racial Category</em> (levels of the X variable), overlaying a
normal curve…</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">hst</span>(data, inc, race)</span></code></pre></div>
<p><img src="anova-example_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<ul>
<li><span style="color:red">We can see from the histogram that for group
distributions of the outcome variable (beers), the data are moderately
positively skewed (with the exception of the distribution of scores for
black individuals). Although these are moderately skewed, it is safe to
assume that these data are close enough to normal to proceed with the
statistical test.</span></li>
</ul>
<p><br></p>
</div>
<div id="b.-boxplots-box-and-whisker-plots" class="section level5">
<h5>4b. Boxplots (Box-and-Whisker Plots)</h5>
<p>Boxplots also provide a visual representation of the normality of a
distribution. The boxplot has a box, a line through the box, two
whiskers on either end of the box, and sometimes dots/points outside the
whiskers. Below, we get a sense of what each part of the boxplot
represents…</p>
<ul>
<li>Bottom (or left end) of the <strong>whisker</strong> represents the
minimum score for that variable’s distribution</li>
<li>Bottom (or left end) of the <strong>box</strong> represents the
first quartile (the 25th percentile case)</li>
<li>Middle line (or dot) inside the <strong>box</strong> represents the
median, also known as the second quartile (the 50th percentile
case)</li>
<li>Top (or right end) of the <strong>box</strong> represents the third
quartile (the 75th percentile case)</li>
<li>Top (or right end) of the <strong>whisker</strong> represents the
maximum score for that variable’s distribution</li>
<li>Outside dots represent outliers - extreme high or extreme low values
for that variable.</li>
</ul>
</div>
</div>
<div id="section" class="section level1">
<h1></h1>
</div>
<div id="section-1" class="section level1">
<h1></h1>
<p>To tell if a variable is normally-distrubted using the
box-and-whisker plot, generally, we want to see that there is
<em>some</em> distance between the box and the end of the whiskers, that
the box isn’t pushed too close to either whisker, that the median line
(dot) is near the center of the box, and that there aren’t many outliers
(dots) on the outside of the whiskers.</p>
</div>
<div id="section-2" class="section level1">
<h1></h1>
<p>To plot a boxplot of <em>Monthly Income</em>, broken out by
<em>Race</em>, we can do the following…</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="fu">box</span>(data, inc, race)</span></code></pre></div>
<p><img src="anova-example_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<ul>
<li><span style="color:red">We can see from the boxplots that for the
black and other groups are somewhat normally distributed. The data for
latinx and white individuals, however, possesses some outliers, and the
median falls near or on the edge of the interquartile range. In
addition, the minimum and maximum scores are missing for latinx
individuals while the maximum is missing for white individuals (rather,
those scores are read as extremes or outliers). These plots may give us
some pause in proceeding. In many cases, finding distributions like this
would warrant further data collection (e.g. there may be too few cases
in this sample, which is why many are perceived as outliers). However,
for this example, the data seem <em>normal enough</em>. It is safe to
assume that these data are close enough to normal, since they aren’t
<em>drastically</em> different from normal, and therefore safe to
proceed with the statistical test.</span> <br></li>
</ul>
<div id="c.-normal-q-q-quantile-quantile-plots" class="section level5">
<h5>4c. Normal Q-Q (Quantile-Quantile) Plots</h5>
<p>The quantile-quantile plot is a visual tool to help us figure out if
the empirical distribution of our variable fits (or rather, comes from)
a theoretical normal distribution.</p>
<p>We assess normality an break this plot out by a grouping
variable.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">qq</span>(data, inc, race)</span></code></pre></div>
<p><img src="anova-example_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<ul>
<li><p><span style="color:red">We can see from the Q-Q plot that for
group distributions of the outcome variable (monthly income), the data
are somewhat normal, since there is no discernible pattern across the
line (e.g. no strong curvilinear trend around normality line) for the
<em>income</em> variable for any group/level (<em>race</em>). It is
therefore safe to proceed with the statistical test.</span></p></li>
<li><p><span style="color:red">Based on the the three visual depictions
above, the data seem normally-distributed.
<code>Therefore, we meet the assumption of normality</code>.</span></p></li>
</ul>
<p><br></p>
</div>
<div id="the-one-way-anova-f-test-calculation" class="section level3">
<h3>The One-Way ANOVA (F-Test) Calculation</h3>
<p>The calculation for the F-Test is:</p>
<p><span class="math inline">\(F = \frac{{MS}_{between}}{{MS}_{within}}
=
\frac{\frac{{SS}_{between}}{df_{between}}}{\frac{{SS}_{within}}{df_{within}}}\)</span></p>
<p>where… <br></p>
<ul>
<li><span class="math inline">\({MS}_{between}\)</span> is the mean
square for the treatment, effect, or between groups<br></li>
<li><span class="math inline">\({MS}_{within}\)</span> is the mean
square for the error, or within groups<br></li>
<li><span class="math inline">\({SS}_{between} = \sum
n_{group}(\bar{X}_{group} - \bar{X}_{total})^2\)</span> is the sum of
squares for the treatment, effect, or between groups; where <span
class="math inline">\(\bar{X}_{total}\)</span> is the grand mean, or the
mean of means<br></li>
<li><span class="math inline">\({SS}_{within} = \sum (X -
\bar{X}_{group})^2\)</span> is the square for the error, or within
groups<br></li>
</ul>
<p>In addition, the degrees of freedom (<span
class="math inline">\(df\)</span>) for the test is…<br> <span
class="math inline">\(df_{between} = k - 1\)</span>; where <span
class="math inline">\(k\)</span> is the number of groups <span
class="math inline">\(df_{within} = N - k\)</span></p>
<p><br></p>
</div>
<div id="running-the-one-way-anova-in-r" class="section level3">
<h3>Running the One-Way ANOVA in R</h3>
<p>To run the one-way ANOVA in R, we take the summary (output) of the
analysis of variance <span style="color:blue"><code>aov</code></span>
function.</p>
<p>For the ANOVA, within the <span
style="color:blue"><code>aov</code></span> function, the dependent
(interval-ratio level) variable is listed first and the independent
(discrete/categorical) variable is listed second, separated by a tilde
<span style="color:blue"><code>~</code></span>.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>ow <span class="ot">&lt;-</span> <span class="fu">ow.anova</span>(data, inc, race, <span class="at">plot =</span> T, <span class="at">hsd =</span> T)</span></code></pre></div>
<p><img src="anova-example_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">summary</span>(ow)</span></code></pre></div>
<pre><code>## Call:
## ow.anova(df = data, var1 = inc, by1 = race, plot = T, hsd = T)
## 
## One-Way Analysis of Variance (ANOVA): 
##                            df      SS      MS      F p-value  
## Between Groups (race)       3 7325888 2441963 4.0429 0.02569 *
## Within Groups (race)       16 9664314  604020                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Tukey&#39;s HSD (Honestly Significant Difference): 
## 
##              Mean Difference       lwr    upr p-value  
## latinx-black        -228.200 -1634.495 1178.1 0.96579  
## other-black          419.800  -986.495 1826.1 0.82793  
## white-black         1354.400   -51.895 2760.7 0.06113 .
## other-latinx         648.000  -758.295 2054.3 0.56513  
## white-latinx        1582.600   176.305 2988.9 0.02480 *
## white-other          934.600  -471.695 2340.9 0.26628  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the output above, we see the F-obtained value (4.043), the degrees
of freedom between and within (3,16), and the p-value (.0257, which is
less than our set alpha level of .05).</p>
<p>To interpret the findings, we report the following information:</p>
<ul>
<li>The test used</li>
<li>If you <strong>reject</strong> or <strong>fail to reject</strong>
the null hypothesis</li>
<li>The variables used in the analysis</li>
<li>The degrees of freedom, calculated value of the test (<span
class="math inline">\(F_{obtained}\)</span>), and <span
class="math inline">\(p-value\)</span>
<ul>
<li><span class="math inline">\(F(df_{between},df_{within}) =
F_{obtained}\)</span>, <span class="math inline">\(p-value\)</span></li>
</ul></li>
</ul>
<p>“Using a one-way ANOVA, I reject/fail to reject the null hypothesis
that there is no mean difference between groups, in the population,
<span class="math inline">\(F(?) = ?, p ? .05\)</span>”</p>
<ul>
<li><span style="color:red">“Using one-way ANOVA, I reject the null
hypothesis that there is no mean difference between the monthly income
of different racial categories, in the population, <span
class="math inline">\(F(3,16) = 4.043, p \lt .05\)</span>”</span></li>
</ul>
<p><br><br></p>
</div>
<div id="post-hoc-checks-which-means-differ" class="section level3">
<h3>Post-Hoc Checks: Which means differ?</h3>
<p>After finding a significant result in your omnibus/overall
F-test/ANOVA, to identify <em>where</em> the differences lie, you can do
two things:</p>
<ul>
<li>Examine a means plot</li>
<li>Run a Post-hoc significance test</li>
</ul>
<div id="means-plot" class="section level4">
<h4>Means Plot</h4>
<p>As seen in the plot above:</p>
<ul>
<li><span style="color:red">Here, we can see that it looks like whites
have higher monthly incomes than others. Yet to see, statistically, if
group means differ, we have to run post-hoc tests that compare all
possible pairs of means to determine which differences are statistically
significant.</span></li>
</ul>
<p><br></p>
</div>
<div id="post-hoc-significance-test-tukeys-hsd" class="section level4">
<h4>Post-Hoc Significance Test: Tukey’s HSD</h4>
<p>As seen in the output above:</p>
<ul>
<li><span style="color:red">Here, we see that the only significant
difference lies between white’s mean monthly income and latinx’ mean
monthly income.</span></li>
</ul>
<p><br><br><br></p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
