<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Chi-Square Test of Independence</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="markdown3.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">RStudio Walkthroughs</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-download"></span>
     
    Getting Started
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="installing.html">Downloading/Installing</a>
    </li>
    <li>
      <a href="getting-started.html">Getting Started with RStudio</a>
    </li>
    <li>
      <a href="reading-in-data.html">Reading in Data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-chart-line"></span>
     
    In-Class
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Univariate Statistics</li>
    <li>
      <a href="univariate-normality.html">Descriptive Statistics and Assessing Normality</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Bivariate Statistics</li>
    <li>
      <a href="t-test.html">Independent Samples t-Test</a>
    </li>
    <li>
      <a href="anova.html">One-Way Analysis of Variance (ANOVA)</a>
    </li>
    <li>
      <a href="chi-square.html">Chi Square Test of Independence</a>
    </li>
    <li>
      <a href="correlation.html">Correlation</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Multivariate Statistics</li>
    <li>
      <a href="regression.html">OLS Regression</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-folder-open"></span>
     
    Additional Materials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Bivariate Statistics</li>
    <li>
      <a href="chi-square-gof.html">Chi Square Goodness of Fit</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Chi-Square Test of Independence</h1>

</div>


<hr />
<p>[
<a href="https://raw.githubusercontent.com/burrelvannjr/gradstats_sdsu/main/resources/exercises/chi-square.R" target="_blank"><i>R
Script</i></a> | <a href="chi-square-example.html"><em>Example</em></a>
]</p>
<div
id="is-there-a-relationship-between-the-shape-of-a-cars-engine-vs-and-its-transmission-type-am"
class="section level4">
<h4>Is there a relationship between the shape of a car’s engine
(<span><code>vs</code></span>) and its transmission type
(<span><code>am</code></span>)?</h4>
<p>Here, we’ll be working from the <span
style="color:blue"><code>mtcars</code></span> data set, to examine the
relationship between the shape of a car’s engine
(<span><code>vs</code></span>: measured 0 for V-shaped engines and 1 for
straight-shaped engines) and its transmission type
(<span><code>am</code></span>: measured 0 for automatic and 1 for
manual).</p>
<p><br></p>
</div>
<div id="what-is-the-chi-square-test-of-independence"
class="section level3">
<h3>What is the Chi Square Test of Independence?</h3>
<p>The Chi Square test (<span class="math inline">\(X^2\)</span>)
examines the association or relationship between two nominal/ordinal
variables to see if the relationship reflects a true relationship that
we could expect to find in the population. The test also tells us
whether or not a category (attribute) of one variable varies by
categories of another variable.</p>
<p>The test is called the <em>test of independence</em> because it
really tests the absence of association between (independence of) two
variables.</p>
<p><br></p>
<div id="load-the-necessary-stuff" class="section level4">
<h4>Load the Necessary Stuff</h4>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(vannstats)</span></code></pre></div>
<p><br></p>
</div>
<div id="reading-in-the-data" class="section level4">
<h4>Reading in the Data</h4>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> mtcars</span></code></pre></div>
<p><br></p>
</div>
</div>
<div id="assumptions-and-diagnostics-for-chi-square"
class="section level3">
<h3>Assumptions and Diagnostics for Chi Square</h3>
<p>The assumptions for the Chi Square are…</p>
<ul>
<li>Independence of Observations</li>
<li>Normality</li>
</ul>
<div id="independence-of-observations-examine-data-collection-strategy"
class="section level5">
<h5>1. Independence of Observations (Examine Data Collection
Strategy)</h5>
<ul>
<li><p>Cases (observations) are not related or dependent upon each
other. Case can’t have more than one attribute. No ties between
observations. Examine data collection strategy to see if there are
linkages between observations.</p>
<ul>
<li><span style="color:red">Given that the mtcars data have been
randomly-sampled,
<code>we have met the assumption of independence of observations</code>.</span></li>
</ul></li>
</ul>
<p><br></p>
</div>
<div
id="normality-examine-expected-frequencies-crosstabcontingency-table"
class="section level5">
<h5>2. Normality (Examine Expected Frequencies Crosstab/Contingency
Table)</h5>
<ul>
<li>Distributions must be relatively normal.The normality assumption is
met if <strong>no more than 20 percent of the cells in our Expected
Frequencies crosstab have fewer than 5 cases.</strong> Therefore, if
(<span class="math inline">\(E \lt 5\)</span>) for more than 20 percent
of the cells in the Expected Frequencies table, the assumption of
normality is violated. If the assmuption of normality is violated, the
researcher can employ Yates’ Continuity Correction, which conservatively
adjusts the numerator for small sample sizes. To employ this correction
in R, simply change the option to <code>correct = TRUE</code>.</li>
</ul>
<p>In the <span style="color:blue"><code>vannstats</code></span>
package, I have included the <span
style="color:blue"><code>tab</code></span> function which returns the
crosstabs of observed and expected frequencies. To check if you’ve met
the assumption of normality (e.g. fewer than 20% of cells in the
crosstab of expected frequencies falls below <span
class="math inline">\(n=5\)</span>), you use the following:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">tab</span>(data1, vs, am)</span></code></pre></div>
<pre><code>## $`Observed Frequencies`
##       am: 0  1 Total
## vs: 0    12  6    18
## 1         7  7    14
## Total    19 13    32
## 
## $`Expected Frequencies`
##         am: 0       1 Total
## vs: 0 10.6875  7.3125    18
## 1      8.3125  5.6875    14
## Total 19.0000 13.0000    32</code></pre>
<ul>
<li><span style="color:red">We see here that
<code>we have met the assumption of normality</code>: less than 20% of
cells in the 2x2 Expected Frequency crosstab have fewer than 5 expected
counts. Actually, no cell has fewer than 5.</span></li>
</ul>
<p><br></p>
</div>
</div>
<div id="the-chi-square-test-calculation" class="section level3">
<h3>The Chi Square Test Calculation</h3>
<p>The calculation for the Chi Square is:</p>
<p><span class="math inline">\(X^2 = \sum \frac{(f_o -
f_e)^2}{f_e}\)</span> or <span class="math inline">\(X^2 = \sum
\frac{(f_{o_i} - f_{e_i})^2}{f_{e_i}}\)</span></p>
<p>where… <br></p>
<ul>
<li><span class="math inline">\(f_o\)</span> (or <span
class="math inline">\(f_{o_i}\)</span>) is the observed frequency for
that cell (the <span class="math inline">\(i^{th}\)</span>cell)<br></li>
<li><span class="math inline">\(f_e\)</span> (or <span
class="math inline">\(f_{e_i}\)</span>) is the expected frequency for
that cell (the <span class="math inline">\(i^{th}\)</span>cell)<br>
<ul>
<li><span class="math inline">\(f_e\)</span> (or <span
class="math inline">\(f_{e_i}\)</span>) for each cell is calculated by
the following:
<ul>
<li><span class="math inline">\(f_e\)</span> (or <span
class="math inline">\(f_{e_i}\)</span>) <span class="math inline">\(=
\frac{(r_{total_i})(c_{total_i})}{total}\)</span> <span
class="math inline">\(=
\frac{(n_{row_i})(n_{column_i})}{N}\)</span></li>
</ul></li>
</ul></li>
</ul>
<p>In addition, the degrees of freedom (<span
class="math inline">\(df\)</span>) for the test is…<br> * <span
class="math inline">\(df = (r-1)(c-1)\)</span></p>
<p>where…</p>
<ul>
<li><span class="math inline">\(r\)</span> is the number of rows in a
crosstabulation<br></li>
<li><span class="math inline">\(c\)</span> is the number of columns in a
crosstabulation<br></li>
</ul>
<p><br></p>
</div>
<div id="running-the-chi-square-test" class="section level3">
<h3>Running the Chi Square Test</h3>
<p>For Chi Square, within the <span
style="color:blue"><code>chi.sq</code></span> function, the dependent
variable is listed first and the independent variable is listed
second.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="co">#chisq.test(data1$vs, data1$am, correct=FALSE)</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>chi <span class="ot">&lt;-</span> <span class="fu">chi.sq</span>(data1, vs, am)</span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a><span class="fu">summary</span>(chi)</span></code></pre></div>
<pre><code>## Call:
## chi.sq(df = data1, var1 = vs, var2 = am)
## 
## Pearson&#39;s Chi-squared test: 
## 
##       χ² Critical χ² df p-value
##  0.90688     3.84100  1  0.3409</code></pre>
<p>In the output above, we see the <span
class="math inline">\(X^2\)</span>-obtained value (0.90688), the degrees
of freedom (1), and the p-value (0.3409, which is greater than our set
alpha level of .05).</p>
<p>To interpret the findings, we report the following information:</p>
<ul>
<li>The test used</li>
<li>If you <strong>reject</strong> or <strong>fail to reject</strong>
the null hypothesis</li>
<li>The variables used in the analysis</li>
<li>The degrees of freedom, calculated value of the test (<span
class="math inline">\(X^2_{obtained}\)</span>), and <span
class="math inline">\(p-value\)</span>
<ul>
<li><span class="math inline">\(X^2(df) = X^2_{obtained}\)</span>, <span
class="math inline">\(p-value\)</span></li>
</ul></li>
</ul>
<p>“Using the Chi Square test of independence (<span
class="math inline">\(X^2\)</span>), I reject/fail to reject the null
hypothesis that there is no association between variable one and
variable 2, in the population, <span class="math inline">\(X^2(?) = ?, p
? .05\)</span>”</p>
<ul>
<li><span style="color:red">“Using the Chi Square test of independence
(<span class="math inline">\(X^2\)</span>), I fail to reject the null
hypothesis that there is no association between the shape and the
transmission type of cars, in the population, <span
class="math inline">\(X^2(1) = .90688, p \gt .05\)</span>” </span></li>
</ul>
<p><br></p>
<div id="yates-continuity-correction-for-the-chi-square-test"
class="section level4">
<h4>Yates’ Continuity Correction for the Chi Square Test</h4>
<p>The calculation for Yates’ Chi Square is:</p>
<p><span class="math inline">\(X^{2}_{Yates&#39;} = \sum \frac{(|f_o -
f_e| - 0.5)^2}{f_e}\)</span> or<br />
<span class="math inline">\(X^{2}_{Yates&#39;} = \sum \frac{(|f_{o_i} -
f_{e_i}| - 0.5)^2}{f_{e_i}}\)</span></p>
<p>To employ Yates’ Continuity Correction, when we have violated the
assumption of normality, simply update the <code>chi.sq</code> option to
<code>correct = TRUE</code>, as below</p>
<p><br></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co">#chisq.test(data1$vs, data1$am, correct=TRUE)</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>chi <span class="ot">&lt;-</span> <span class="fu">chi.sq</span>(data1, vs, am, <span class="at">post =</span> T)</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a><span class="fu">summary</span>(chi)</span></code></pre></div>
<p><br><br></p>
</div>
</div>
<div id="post-hoc-checks-which-cells-differ" class="section level3">
<h3>Post-Hoc Checks: Which cells differ?</h3>
<p>After finding a significant result in your omnibus/overall chi square
test, to identify <em>where</em> the differences lie, you can do one
thing:</p>
<ul>
<li>Run a Post-hoc significance test, using</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>chi <span class="ot">&lt;-</span> <span class="fu">chi.sq</span>(data1, vs, am, <span class="at">post =</span> T)</span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a><span class="fu">summary</span>(chi)</span></code></pre></div>
<pre><code>## Call:
## chi.sq(df = data1, var1 = vs, var2 = am, post = T)
## 
## Pearson&#39;s Chi-squared test: 
## 
##       χ² Critical χ² df p-value
##  0.90688     3.84100  1  0.3409
## 
## 
## Post-Hoc Test w/ Bonferroni Adjustment:
## Comparing: am-vs 
## 
##     Standardized Residual (Z) p-value
## 0-0                    0.9523       1
## 0-1                   -0.9523       1
## 1-0                   -0.9523       1
## 1-1                    0.9523       1</code></pre>
<p><br></p>
<div id="post-hoc-significance-test" class="section level4">
<h4>Post-Hoc Significance Test</h4>
<p>And finally, we can see where the <em>significantly different</em>
different comparisons (between observed and expected) are, Bonferroni’s
adjusted p-values which can also be called from the <span
style="color:blue"><code>chi.sq</code></span> function. As seen
above:</p>
<ul>
<li><span style="color:red">Here, we see that none of the comparisons –
between observed and expected cells – significantly differ.</span></li>
</ul>
<p><br><br><br></p>
<p><br><br><br></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
